Implement "basic" Mastic
jimouris/draft-mouris-cfrg-mastic pull request #20
Opened 2023-10-17 00:12 UTC by cjpatton

Add a new module to `poc` that implements the Mastic VDAF. This VDAF is similar to Poplar1 except that instead of aggregating counters, Mastic can aggregate any data type that is compatible with FlpGeneric.

Mastic operates in one of two "modes", depending on how the VIDPF is configured. In "incremental mode", the FLP is checked when evaluating at the first level of the VIDPF tree; in non-incremental mode, the FLP is checked when evaluating the last level of the tree (all intermediate levels are disabled).

When verifying the FLP, the encoded measurement (i.e., `beta`) is computed by evaluating the VIDPF at both child nodes of the root and summing the output shares. By one-hot verifiability, this sum is equal to value claimed by the Client; by path verifiability, checking this value is sufficient each node on the `alpha` path is guaranteed to have the same value.

The code is incomplete but is sufficient to illustrate the basic features we want. Some things to do:

* Add support for circuits with joint randomness

* Specify `PublicShare` and `InputShare`

* Decide whether to bind the query randomness to the VIDPF mode

* Implement message serialization

2023-10-17 00:23 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            # propagated along the entire `alpha` path.
@jimouris please confirm that these "one-hot" and "path" verifiability are properties claimed by VIDPF.

2023-10-17 00:23 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            # doesn't add communication cost.
@jimouris, @hannahdaviscrypto what would you like to do here? In the Overleaf version of the protocol, we evaluate the VIDPF "at the root" (i.e.,at the empty string $\varepsilon$), but this doesn't seem to be possible with the current VIDPF API. (I think Hannah was working on some changes to VIDPF that would have allowed this, but it wasn't compiling and I'm not sure how far she got with it.)

Evaluating at both children and then summing (as we do here) has a bit of CPU overhead. However it also has some advantages:
1. It's simple to specify
2. It has zero communication overhead. (If evaluating at the root, would we need to send more information in the public share so that the Aggregators can reconstruct shares of the output?)
3. It involves at most one more call to `Vidpf.eval_next()` than is necessary. (If `0` is not a prefix of any string in `prefixes`, then it'll be a waste to evaluate it.)

2023-10-17 13:25 UTC, jimouris commented on poc/vdaf_mastic.py
> +USAGE_QUERY_RAND = 0
Nit: Can you add a comment to describe what these three are? Also, maybe an `enum` would be cleaner?

2023-10-17 13:27 UTC, jimouris commented on poc/vdaf_mastic.py
> +        proof = cls.Flp.prove(beta, prove_rand, [])
What is the last argument [] here?

2023-10-17 13:28 UTC, jimouris commented on poc/vdaf_mastic.py
> +        if cls.Vidpf.INCRIMENTAL_MODE:
Rename to `INCREMENTAL_MODE`.

2023-10-17 13:41 UTC, jimouris commented on poc/vdaf_mastic.py
> +            # propagated along the entire `alpha` path.
> It is sufficient to check the proof over the sum of the outputs, since the one-hot verifiability property of VIDPF ensures that exactly one of the children is equal to the encoded `beta` (and the other is equal to `0`).

Yeah, that's correct. Just to clarify, this holds if the proofs from both servers are equal.

> It is sufficient to check the proof just once since the path verifiability property of VIDPF ensures that the same `beta` is propagated along the entire `alpha` path.

The path verifiability does not rely on the VIDPF proofs, we get this from the PLASMA parent-children checks. I'd rephrase it to:
```
Path Verifiability: This property ensures that the same `beta` is propagated along the entire `alpha` path. Additionally, for all other evaluations that are not `alpha` (or prefixes of it), we get zero.
```

I'd also add the **One-hot Verifiability:** and **Path Verifiability:** in front of each to make it clear that we rely on these properties.

2023-10-17 13:46 UTC, jimouris commented on poc/vdaf_mastic.py
> +            raise Exception('output vector is not one-hot')
How about?
```python
raise Exception('Path Verifiability Error: The output vector is not one-hot.')
```

2023-10-17 13:47 UTC, jimouris commented on poc/vdaf_mastic.py
> +    def prep_next(Prio3, prep_state, prep_msg):
Prio3?

2023-10-17 13:52 UTC, jimouris commented on poc/vdaf_mastic.py
> +    @classmethod
Who runs `is_valid()`? I'm a bit confused about what it checks.

2023-10-17 13:57 UTC, jimouris commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
`out_share[0]` and `out_share[1]` are the left and right children, right? Then we add them into `meas_share` and check the FLP, correct? But the full evaluation happens in lines 105-112? Shouldn't we have a check like:

```python
if level == 0:
# check FLP
else:
# do parent-children checks
```

2023-10-17 13:58 UTC, jimouris requested changes
Looks good, thanks for putting it together! I added some suggestions, some questions, and some nits.

2023-10-17 14:34 UTC, cjpatton commented on poc/vdaf_mastic.py
> +        proof = cls.Flp.prove(beta, prove_rand, [])
joint randomness (currently empty)

2023-10-17 14:35 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            # doesn't add communication cost.
can you send a PR with the necessary change to `vidpf`?

2023-10-17 14:36 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            raise Exception('output vector is not one-hot')
This isn't Path Verifiability though, right? This is One-hot Verifiability.

2023-10-17 14:37 UTC, cjpatton commented on poc/vdaf_mastic.py
> +    @classmethod
See https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-07#section-5.3

2023-10-17 14:38 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            # doesn't add communication cost.
Err actually what do you mean by "latter"? If you want to evaluate at $\varepsilon$ (I agree this is cleaner) then I believe we need to change the API. Or am I misunderstanding something?

2023-10-17 14:40 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
I claim that you always want to do VIDPF verification and only do FLP verification once.

2023-10-17 15:11 UTC, jimouris commented on poc/vdaf_mastic.py
> +            # propagated along the entire `alpha` path.
Correct. We only need 1 FLP to check \epsilon (or left and right) as you did, and then we'll need the parent-children checks to check that this beta value is propagated correctly. Something like: https://github.com/jimouris/mastic/blob/main/src/collect.rs#L246

2023-10-17 15:13 UTC, jimouris commented on poc/vdaf_mastic.py
> +            # doesn't add communication cost.
I meant that I prefer evaluating the 2 children. VIDPF won't need any changes either.

2023-10-17 15:14 UTC, jimouris commented on poc/vdaf_mastic.py
> +            raise Exception('output vector is not one-hot')
Correct, I meant *One-hot* verifiability.

2023-10-17 15:18 UTC, jimouris commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
I might misunderstood something. By VIDPF verification you mean check the proofs? Yes, we should do that at every level. Additionally, we'd need to do the parent-children checks at every level to make sure that the beta value (which we verified is valid in level 0) is propagated correctly down the tree.

2023-10-17 15:41 UTC, jimouris commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
Exactly. From Overleaf:

> So far, with VIDPF, the servers can verify that there is at most one non-zero output at each level. However, VIDPFs alone are not sufficient to guarantee that the keys are well formed. The servers still need to verify that: a) the non-zero values of the client are
across a single path in the binary tree, and b) the value of the root node is correctly propagated down the VIDPF tree. We formalize these requirements as an additional property: Path Verifiability: blah blah blah

The idea is that we want $y^γ - (y^{γ||0} + y^{γ||1}) = 0$. Then the following should hold:
$y_0^γ - y_0^{γ||0} - y_0^{γ||1} = - y_1^γ + y_1^{γ||0} + y_1^{γ||1}$. So each server computes their part (server 0 computes the left and server 1 computes the right) and they check if it's correct.

2023-10-17 15:43 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
Ohhhh that's so beautifully simple. I think you already mentioned this at some point but it didn't bleed through.

To implement this, I think we need to to take @hannahdaviscrypto's changes to `vidpf`. I'll work on this.

2023-10-17 15:47 UTC, jimouris commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
Thanks :) It might make more sense to do it on the mastic-vdaf level rather than in VIDPF. This might help as well: https://github.com/jimouris/mastic/blob/main/src/collect.rs#L246

2023-10-17 19:56 UTC, jimouris approved these changes

2023-10-17 23:39 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
I ended up extending VIDPF (see top-comment for justification): https://github.com/jimouris/draft-mouris-cfrg-mastic/pull/22

2023-10-17 23:41 UTC, cjpatton commented
Rebased (on #22) and squashed.

2023-10-17 23:52 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            # propagated along the entire `alpha` path.
Done.

2023-10-18 19:52 UTC, cjpatton commented on poc/vdaf_mastic.py
> +        (out_share, level_proof) = cls.Vidpf.eval(agg_id,
We could eliminate it, but we'd need to make changes to `Vidpf`. In particular, we need to be able to compute our share of `beta`. Perhaps we could have `Vidpf` return `prefix_tree_share`?

2023-10-18 19:56 UTC, jimouris commented on poc/vdaf_mastic.py
> +        (out_share, level_proof) = cls.Vidpf.eval(agg_id,
What do you mean, why? Isn't that the `out_share`?

2023-10-18 19:59 UTC, cjpatton commented on poc/vdaf_mastic.py
> +        (out_share, level_proof) = cls.Vidpf.eval(agg_id,
To check the FLP we have to compute a share of `beta`. The way we do that here is by evaluating the VIDPF at the children of the root and adding them up.

2023-10-18 20:00 UTC, jimouris approved these changes

2023-10-18 20:49 UTC, cjpatton commented
Rebased.

2023-10-18 20:50 UTC, merged

2023-10-18 21:07 UTC, hannahedavis commented on poc/vdaf_mastic.py
> +            #
I think it might make more sense to do something like a 'fast-forward' approach rather than a fast-start. Even if we were to start at level 7 in this way, we'd still have to evaluate the entire tree and the FLP at level 0. So we could think about changing the agg_param format to a tuple of agg_params; is_valid would evaluate the same properties on the union of the tuples as it currently does. That way you could just evaluate levels 0 and 7 at once and then move on.

2023-10-18 21:17 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            raise Exception('output vector is not one-hot')
Please send a PR to fix since this got merged already!

2023-10-18 21:19 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            #
Sounds reasonable. At this stage I don't want to overcomplicate the spec, so I suggest documenting this idea in an issue. You might also consider updating this comment in a PR.

2023-10-18 21:19 UTC, cjpatton commented on poc/vdaf_mastic.py
> +            meas_share = vec_add(out_share[0], out_share[1])
Sounds reasonable.

2023-10-18 21:20 UTC, cjpatton commented on poc/vidpf.py
> +        path_proof = sha3.digest()
Right. I attempted to address with an "implementation note" above. Basically you can cache the `prefix_tree_share` across calls to `eval()`. Does this ake sense?

2023-10-18 21:22 UTC, cjpatton commented on poc/vidpf.py
> +        path_proof = sha3.digest()
https://github.com/jimouris/draft-mouris-cfrg-mastic/blob/main/poc/vidpf.py#L109