Call `Vidpf.eval()` exactly once
jimouris/draft-mouris-cfrg-mastic pull request #27
Opened 2023-10-20 17:45 UTC by cjpatton

Modify `Vidpf.eval()` so that it returns a share of `beta`, thereby avoiding an extra call during `Mastic.prep_init()` for checking the FLP. We already have this as a result of evaluating the prefix tree.

2023-10-20 17:57 UTC, cjpatton commented on poc/vidpf.py
> +            beta_share = vec_neg(beta_share)
Just to follow up on the issue from the call: We need to negate aggregator 1's share; I was negating 0's.

2023-10-20 17:57 UTC, jimouris requested changes

2023-10-20 17:57 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Ah, great! Just an observation/Question, in case the prefix == '', then `beta_share == out_share`, right?

In this case, would it make sense to check in mastic if level == 0 and then add the out_share[0] (left) and out_share[1] (right) to compute the beta_share? In all other cases, we don't do anything.

2023-10-20 17:58 UTC, jimouris commented on poc/vidpf.py
> +            beta_share = vec_neg(beta_share)
Yup, saw that :)

2023-10-20 17:59 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
`level == 0` is **not** the root, but the children of the root.

2023-10-20 18:04 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Sure, but the comment is still valid. I meant that in the case that the following is true:

```python
if cls.do_range_check(agg_param):
```

then, beta_share == out_share[0] + out_share[1]. Or not? If yes, we can skip the beta_share altogether.

2023-10-20 18:19 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Yes, if `prefix == [0, 1]` and `level == 0` then computing `beta_share` here is redundant and we could instead compute it the way you describe. I've updated `Vidpf.eval()` accordingly.

2023-10-20 18:21 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Thanks, can we move it out of vidpf to mastic_vdaf? This way, if we put the check there we won't have to return both beta_share and out_share, only one would be sufficient.

2023-10-20 18:22 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
But then we'd have to modify `Vidpf.eval()` to conditionally compute `beta_share`, right? That seems overly complicated.

2023-10-20 18:24 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
`Vidpf.eval()` can be as we had it before and we can do the negation in mastic_vdaf. We can merge this one and I can take a stab at it later.

2023-10-20 18:26 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Hmmm, I'm not sure exactly what you're after. Maybe tack on a commit to this branch?

2023-10-20 18:34 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Take a look here: https://github.com/jimouris/draft-mouris-cfrg-mastic/commit/f5088c1b9292d602498cac8f12db3ee83cd8567e

I think that's sufficient, right?

2023-10-20 18:57 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
No because `out_share[0]` is not guaranteed to be the output share for `prefix == 0`. (Similarly for `out_share[1]`.)

2023-10-20 18:57 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Suppose `prep_init()` is called on `prefixes == [0b11], level == 1`.

2023-10-20 18:58 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
But then `if cls.do_range_check(agg_param):` this would be false so we don't really care.

2023-10-20 19:00 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Take a look again: What values of `prefixes` and `level` are permitted if `INCREMENTAL_MODE==False`?

2023-10-20 19:00 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Ah, no it wouldn't be because we have `level == cls.Vidpf.BITS-1`. But do we need that? Why not check just for the level there?

2023-10-20 19:07 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
What do you mean check for the level?

2023-10-20 19:11 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
I meant in `do_range_check` to only check if `level == 0`. I don't see why we need the `INCREMENTAL_MODE` there or even the `level == cls.Vidpf.BITS-1` check.

Maybe it's a good idea to add some tests at some point so if changes like my proposed one don't make sense the tests should catch this.

2023-10-20 19:14 UTC, cjpatton commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Agreed, I don't think I've been clear enough about how I'd like to use Mastic beyond heavy hitters. Let me tack on some commits that will hopefully clarify.

@hannahdaviscrypto, I'm going to remove INCREMENTAL_MODE for now, which means you'll need to rework #25 a bit.

2023-10-20 19:15 UTC, jimouris approved these changes

2023-10-20 19:17 UTC, jimouris commented on poc/vidpf.py
> +        return (beta_share, out_share, pi_proof + path_proof)
Thanks, you explained it before but I didn't fully get it. Maybe it would make sense to add it back once we have these examples/tests.

2023-10-20 21:27 UTC, jimouris approved these changes

2023-10-20 22:57 UTC, merged

2023-10-21 04:45 UTC, hannahdaviscrypto reviewed
This looks good! I have some concerns that the agg_param validity check is too broad but I'm going to attempt a fix in a separate PR, possibly in concert with the tuple idea if I have enough time.