vidpf: Align API with draft
jimouris/draft-mouris-cfrg-mastic pull request #29
Opened 2023-10-22 18:18 UTC by cjpatton

2023-10-22 23:32 UTC, jimouris requested changes

2023-10-22 23:32 UTC, jimouris commented on poc/vidpf.py
> +        pi_proof = cls.ROOT_PROOF
The reason that I was passing the proof as an argument here is that we can take the previous proof and update it. Here we're only reading the ROOT_PROOF but we're not updating anywhere, right? Or I missed it?

2023-10-23 03:38 UTC, hannahdaviscrypto commented on poc/vidpf.py
> +        pi_proof = cls.ROOT_PROOF
I believe so; the ROOT_PROOF is just a constant taking the place of the empty string in the original PLASMA design.

2023-10-23 04:13 UTC, hannahdaviscrypto approved these changes
Looks good to me!

2023-10-23 04:13 UTC, hannahdaviscrypto commented on poc/vidpf.py
In main() lines 278-281 and 323-326, I don't think we need to initialize proofs to contain two copies of ROOT_PROOF. Since the class now computes that for us and initializes pi_proof in eval automatically, I think we could just set proofs = [None, None]. But it's not going to hurt anything.

2023-10-23 14:31 UTC, cjpatton commented on poc/vidpf.py
Good catch.

2023-10-23 14:34 UTC, cjpatton commented on poc/vidpf.py
> +        pi_proof = cls.ROOT_PROOF
That's right, but for Mastic we weren't updating the proof either, so I expect this to be a non-breaking change.

If we think that starting evaluation with an arbitrary proof would be useful, then we can add this back to the API when we need it.

2023-10-23 14:55 UTC, merged