Editorial changes
jimouris/draft-mouris-cfrg-mastic pull request #50
Opened 2023-12-07 21:45 UTC by divergentdave

This makes a few editorial changes from my first read-through of the document and proof of concept implementation. See the individual commit messages for explanations.

2023-12-07 23:10 UTC, cjpatton approved these changes

2023-12-10 14:04 UTC, jimouris commented on draft-mouris-cfrg-mastic.md
> +   that the sum is equal to the Aggregator's share of `beta`.
This one is a bit tricky as one-hotness alone implies only that the sum is non-zero at one position. We need both properties together to be sure that this non-zero value is indeed `beta` (which we have checked at the root with the FLP).

2023-12-10 14:09 UTC, jimouris requested changes
Looks great, thanks for reading through it! I only have the small comment about one-hotness + path verifiability.

2023-12-11 23:30 UTC, jimouris approved these changes

2023-12-18 22:15 UTC, merged